import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/elements/navbar'
import Footer from '@/components/elements/footer'
import Container from '@/components/container'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${inter.className} min-h-screen flex flex-col justify-between`}
      >
        <Navbar />
        <Container className='flex-1'>{children}</Container>
        <Footer />
      </body>
    </html>
  )
}
